"""Intial migration

Revision ID: 55cbd02e1e9e
Revises: 
Create Date: 2023-01-26 14:54:52.168157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55cbd02e1e9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('woman_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('women',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Rate', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=20), nullable=False),
    sa.Column('Position', sa.String(length=20), nullable=True),
    sa.Column('Company', sa.String(length=20), nullable=False),
    sa.Column('Country', sa.String(length=20), nullable=False),
    sa.Column('Birth_date', sa.String(length=20), nullable=False),
    sa.Column('About', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('women')
    op.drop_table('reviews')
    # ### end Alembic commands ###
